<a href="https://colab.research.google.com/github/RocioRodriguez13/Data-Science-Ingenias-2025/blob/main/NotebooksN5_RodriguezRocio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
# Importamos la biblioteca Numpy
import numpy as np

In [ ]:
# Ejericio 1
vector1 = np.zeros(10)
print(vector1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Ejercicio 2
# Crea un arrelgo de longitud 10 con ceros en todas las posiciones y un 10 en la posicion numero 5
vector2 = np.zeros(10)
#arregl de 10 ceros
vector2[4] = 10
#en la posicion 4 ubicamos  el 10
print(vector2)


[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
# Ejercicio 3
# Crear un arreglo que tenga los números del 10 al 49

arreglo3 = np.arange(10,50)
print(arreglo3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Ejercicio 4
# Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
arreglo4 = np.arange(9).reshape(3,3)

print(arreglo4)
print(arreglo4.ndim)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


In [ ]:
# Ejercicio 5
# Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza.
print("creacion de longuitud aleatorio de 100 ")
arreglo5 = np.random.randn(100)
print(arreglo5)
print ()
print("creacion de media ")
media = np.mean(arreglo5)
print(media)
print()
print("creacion de varianza ")
varianza = np.var(arreglo5)
print(varianza)

creacion de longuitud aleatorio de 100 
[-1.10807240e+00 -6.26143222e-01 -1.08482234e+00 -1.31629579e+00
  4.69964681e-01 -9.78917976e-02 -1.86939721e+00  6.96861836e-01
  2.56129287e-01  1.50221560e+00  1.13785694e+00  6.43546763e-02
  4.14917593e-01 -1.48311573e-01 -2.50156302e-02  1.76919677e-01
 -1.58453758e-01  1.08579362e+00 -5.51140303e-01 -2.85719591e-02
  1.30024211e+00 -1.12338225e+00  1.00086349e+00  5.22980721e-01
  3.16541497e-01  6.29484466e-01  1.09488545e-01  9.96029500e-01
  1.10090647e+00  1.41149222e+00 -6.08404666e-01 -1.30176622e+00
 -1.35810487e-01 -5.45237104e-01  1.91484294e-01 -7.72140017e-02
 -1.67392388e+00  5.50125490e-02 -4.72432441e-01 -8.33558944e-01
  9.21198600e-01 -7.98168115e-01 -2.58909267e+00 -2.46880919e-02
  7.85043731e-02 -1.55160384e+00 -1.60111187e-01 -1.64483258e+00
  5.63365202e-01  1.93875587e-03 -4.30801112e-01 -8.31875135e-01
 -2.35030604e+00  1.10489834e+00  1.15367434e-01 -1.11247709e+00
  1.21737738e+00 -4.75967696e-01 -3.78620755e-02 -

In [ ]:
# Ejericio 6
# Calcular la media de un arreglo usando np.sum

vector6 = np.array([1,2,3,4,10])
media = np.sum(vector6)/len(vector6)
#print(len(arry))

print(media)


4.0


In [ ]:
# Ejercicio7
# Calcular la varianza de un arreglo usando np.sum y np.mean
print("Creacion de varianza de un arreglo usando np.sum y n.mean")
arreglo7 = np.array([1,2,3,4,10])
varianza = np.sum((arreglo7-np.mean(arreglo7))**2)/len(arreglo7)
print(varianza)


arreglo7 = np.array([1,2,3,4,10])
varianza = np.sum((arreglo7-np.mean(arreglo7))**2)/(len(arreglo7)-1)

print(varianza)

creacion de vianza de un arreglo usando np.sum y n.mean
10.0
12.5


In [ ]:
# Ejercicio 8
# Crear un array de números aleatorios usando np.random.randn
print("creacion de un array de numeros aleatorios ")
array_aleatorio = np.random.randn(10)
print(array_aleatorio)


creacion de un array de numeros aleatorios 
[ 0.68571565 -0.67486645 -0.70692277  0.12474701 -1.77756882 -0.0054713
  0.20554548 -1.46874191 -0.35159226  0.26333984]
